const languageTips: string[] = [
  "Watch your favorite movies with subtitles in the target language.",
  "Listen to podcasts hosted by native speakers during your commute.",
  "Switch your phone’s system language to the language you are learning.",
  "Read children’s books to build a foundation of basic vocabulary.",
  "Follow social media accounts that post content in your target language.",
  "Watch cooking tutorials to learn practical, everyday verbs.",
  "Listen to local radio stations from countries where the language is spoken.",
  "Read news articles written in simple, clear language.",
  "Watch vlogs to hear natural, conversational slang.",
  "Listen to audiobooks while following along with the physical text.",
  "Record yourself reading a paragraph and compare it to a native speaker.",
  "Talk to yourself out loud while performing daily chores.",
  "Use voice-to-text features to check if your pronunciation is accurate.",
  "Find a language exchange partner for weekly video calls.",
  "Repeat phrases immediately after hearing them in a video.",
  "Focus on mastering the specific sounds (phonemes) that are new to you.",
  "Practice tongue twisters to improve your mouth muscle coordination.",
  "Narrate your day as if you are a character in a movie.",
  "Sing along to songs to improve your rhythm and intonation.",
  "Join a local or online conversation club.",
  "Write a daily journal entry about what you did that day.",
  "Use flashcards to practice the most frequent 1,000 words.",
  "Label items around your house with sticky notes containing their names.",
  "Write shopping lists in your target language.",
  "Translate a song’s lyrics to understand deeper meaning and metaphors.",
  "Keep a vocabulary notebook categorized by theme.",
  "Write short reviews of books or movies you have finished.",
  "Use mnemonics to help memorize complex vocabulary words.",
  "Draft emails to yourself to practice formal writing styles.",
  "Comment on social media posts in the language you are learning.",
  "Study the grammar rules through short, focused daily lessons.",
  "Break down complex sentences to understand their structure.",
  "Analyze the differences between formal and informal speech.",
  "Work through a structured language learning textbook.",
  "Use spaced repetition software to keep your memory sharp.",
  "Take short quizzes to test your comprehension of new grammar.",
  "Focus on learning common collocations (words that go together naturally).",
  "Create a mind map to connect related vocabulary words.",
  "Compare a paragraph in your language with its translation in the target language.",
  "Practice conjugating verbs in different tenses for 10 minutes a day.",
  "Think in your target language instead of translating from your native one.",
  "Play video games with the dialogue set to the language you are learning.",
  "Cook a recipe by following instructions written in the target language.",
  "Learn about cultural idioms to sound more like a native speaker.",
  "Teach a simple concept to a friend to reinforce your own knowledge.",
  "Volunteer for tasks that require communication in your target language.",
  "Listen to music and try to identify the theme of the song.",
  "Watch documentaries about the history of the language.",
  "Find a pen pal to exchange letters with regularly.",
  "Make a list of your goals to track your progress over the next month.",
  "Use apps that focus on speaking games rather than just typing.",
  "Try to summarize a movie plot in just three sentences.",
  "Look up the etymology of new words to remember them better.",
  "Take a language proficiency practice test once every few months.",
  "Attend a cultural event where you can hear the language spoken in public.",
  "Keep a list of phrases you hear native speakers use repeatedly.",
  "Use a digital whiteboard to sketch out grammar concepts.",
  "Find a song you love and memorize the chorus.",
  "Create flashcards for common phrasal verbs.",
  "Try reading the same news article in two different languages.",
  "Spend 15 minutes a day writing short stories.",
  "Record a monologue about your career goals.",
  "Listen to children's lullabies to get used to basic sentence patterns.",
  "Practice polite forms of address to sound more respectful.",
  "Use post-it notes to label every object in your kitchen.",
  "Join a forum related to your hobbies in your target language.",
  "Watch TED talks with transcripts on for deep listening practice.",
  "Practice answering common interview questions in the target language.",
  "Try to identify the gender of every noun you see for a week.",
  "Listen to comedy sketches to understand cultural humor.",
  "Read poetry to appreciate the rhythm of the language.",
  "Watch travel vlogs about countries where the language is native.",
  "Try to explain a complex topic using only simple vocabulary.",
  "Engage in a 'no-English' hour at home with a partner.",
  "Use a dictionary app that provides usage examples for every word.",
  "Watch a movie you know well in its original, then switch to the dubbed version.",
  "Search for 'easy' versions of classic literature in your target language.",
  "Record yourself retelling a story you read earlier in the day.",
  "Practice reading menus from foreign restaurants online.",
  "Download a keyboard layout for your target language.",
  "Use autocorrect in the target language to help with spelling.",
  "Take notes during a lecture in your target language.",
  "Read the user manual of your electronics in the target language.",
  "Translate your daily to-do list into your target language.",
  "Find a group of language learners on Discord to chat with.",
  "Listen to historical podcasts to learn about the culture.",
  "Try to guess the meaning of unknown words from context before looking them up.",
  "Write thank-you notes for friends in the target language.",
  "Practice using connecting words to make your speech flow better.",
  "Learn to count and perform basic math in the target language.",
  "Watch weather reports to learn geography-related vocabulary.",
  "Follow the news on social media to keep up with current events.",
  "Write an essay about why you are learning the language.",
  "Use a voice recording app to track your progress over months.",
  "Try reading comic books for visual context.",
  "Memorize a short quote that inspires you.",
  "Practice giving directions to a fictional tourist.",
  "Create a PowerPoint presentation about your favorite hobby.",
  "Listen to regional accents to improve your listening flexibility.",
  "Try playing word games like Scrabble in the target language."
];

export function getRandomTip(): string {
  const randomIndex = Math.floor(Math.random() * languageTips.length);
  return languageTips[randomIndex];
}