llama-server.exe ^
    -m C:\models\gemma-4-E2B-it-qat-UD-Q4_K_XL.gguf ^
    --model-draft C:\models\gemma-4-E2B-it-Q4_0-MTP.gguf ^
    --spec-type draft-mtp ^
    --spec-draft-n-max 4 ^
    -ngl 999 ^
    -fa off ^
    -c 22768 ^
    --temp 0.7 ^
    --top-p 0.95 ^
    --top-k 64 ^
    --port 8081